name: Check Commit Message

on: [pull_request, push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Check commit
        uses: adityaa30/check-commit@master
